// Seed script for IEP Continental Americano - Spring Boot backend
// Run with:
// mongosh "mongodb+srv://<user>:<password>@cluster0.nombk2e.mongodb.net/iep_continental_db?retryWrites=true&w=majority&appName=Cluster0" seed.js
db = db.getSiblingDB('iep_continental_db');

// Clean academic/domain collections. Core users are preserved because their
// BCrypt passwords are generated by Spring Boot through /api/auth/register.
[
  'institutions', 'academicyears', 'gradelevels', 'subjects', 'classrooms',
  'students', 'teachers', 'parents',
  'coursesections', 'courses', 'enrollments', 'grades', 'attendances',
  'evaluations', 'events', 'justifications', 'locations', 'notifications'
].forEach(name => db[name].deleteMany({}));

// Messaging is out of scope for IEP Continental Americano — drop any legacy data
db.messages.deleteMany({});
db.conversations.deleteMany({});

function requireUser(email) {
  const user = db.users.findOne({ email });
  if (!user) {
    throw new Error(`Required user not found: ${email}. Register it through /api/auth/register first.`);
  }
  return user._id;
}

const adminId = requireUser("admin@iepca.edu.pe");
const docenteId = requireUser("docente@iepca.edu.pe");
const padreId = requireUser("padre@iepca.edu.pe");
const alumnoId = requireUser("alumno@iepca.edu.pe");

// Extra demo users inserted directly for admin CRUD screens.
// Password hash for "Test1234!" - BCrypt(10)
const passHash = "$2a$10$LKnICS1XVH6.GCFsGnQzm.xKPWGRX8BXjG4IcRqLT3L5RQhE7WUKy";

const docente2Id = ObjectId();
const docente3Id = ObjectId();
const alumno2Id = ObjectId();
const alumno3Id = ObjectId();
const alumno4Id = ObjectId();
const alumno5Id = ObjectId();
const padre2Id = ObjectId();

db.users.deleteMany({
  email: {
    $in: [
      "ana.garcia@iepca.edu.pe",
      "pedro.sanchez@iepca.edu.pe",
      "sofia.ramirez@iepca.edu.pe",
      "diego.torres@iepca.edu.pe",
      "lucia.mendoza@iepca.edu.pe",
      "mateo.herrera@iepca.edu.pe",
      "roberto.ramirez@iepca.edu.pe"
    ]
  }
});

db.users.insertMany([
  { _id: docente2Id, firstName: "Ana", lastName: "Garcia", email: "ana.garcia@iepca.edu.pe", password: passHash, dni: "22334455", phone: "998877661", role: "docente", isActive: true, isVerified: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: docente3Id, firstName: "Pedro", lastName: "Sanchez", email: "pedro.sanchez@iepca.edu.pe", password: passHash, dni: "33445566", phone: "998877662", role: "docente", isActive: true, isVerified: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: alumno2Id, firstName: "Sofia", lastName: "Ramirez", email: "sofia.ramirez@iepca.edu.pe", password: passHash, dni: "66778899", phone: "998877663", role: "estudiante", isActive: true, isVerified: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: alumno3Id, firstName: "Diego", lastName: "Torres", email: "diego.torres@iepca.edu.pe", password: passHash, dni: "77889900", phone: "998877664", role: "estudiante", isActive: true, isVerified: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: alumno4Id, firstName: "Lucia", lastName: "Mendoza", email: "lucia.mendoza@iepca.edu.pe", password: passHash, dni: "88990011", phone: "998877665", role: "estudiante", isActive: true, isVerified: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: alumno5Id, firstName: "Mateo", lastName: "Herrera", email: "mateo.herrera@iepca.edu.pe", password: passHash, dni: "99001122", phone: "998877666", role: "estudiante", isActive: true, isVerified: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: padre2Id, firstName: "Roberto", lastName: "Ramirez", email: "roberto.ramirez@iepca.edu.pe", password: passHash, dni: "44556677", phone: "998877667", role: "padre", isActive: true, isVerified: true, createdAt: new Date(), updatedAt: new Date() },
]);

print("✓ Users created");

// ===== 1. INSTITUTION =====
const instId = ObjectId();
db.institutions.insertOne({
  _id: instId,
  name: "IEP Continental Americano",
  code: "IEPCA001",
  logo: null,
  address: { street: "Av. Continental 456", district: "Continental Americano de Porres", city: "Lima", region: "Lima", postalCode: "15100" },
  phone: "01-5551234",
  email: "info@iepca.edu.pe",
  website: "https://www.iepca.edu.pe",
  director: adminId.toString(),
  evaluationSystem: { type: "bimestral", periodsPerYear: 4, periodNames: ["Bimestre I", "Bimestre II", "Bimestre III", "Bimestre IV"] },
  gradeScale: { type: "vigesimal", minGrade: 0, maxGrade: 20, passingGrade: 11 },
  shifts: ["Mañana", "Tarde"],
  academicLevels: { initial: { from: 3, to: 5 }, primary: { from: 1, to: 6 }, secondary: { from: 1, to: 5 } },
  maxSectionsPerGrade: 4,
  defaultClassroomCapacity: 35,
  evaluationTypes: ["examen", "tarea", "practica", "proyecto", "participacion"],
  defaultEvaluationWeights: { examen: 40, tarea: 20, proyecto: 20, participacion: 10, practica: 10 },
  isActive: true,
  createdAt: new Date(),
  updatedAt: new Date()
});
print("✓ Institution created");

// ===== 2. ACADEMIC YEAR =====
const ayId = ObjectId();
db.academicyears.insertOne({
  _id: ayId,
  institution: instId.toString(),
  year: 2025,
  name: "Año Académico 2025",
  startDate: new Date("2025-03-03"),
  endDate: new Date("2025-12-19"),
  periods: [
    { name: "Bimestre I", number: 1, startDate: new Date("2025-03-03"), endDate: new Date("2025-05-09"), isActive: false, gradesLocked: false, status: "finalizado" },
    { name: "Bimestre II", number: 2, startDate: new Date("2025-05-12"), endDate: new Date("2025-07-18"), isActive: true, gradesLocked: false, status: "activo" },
    { name: "Bimestre III", number: 3, startDate: new Date("2025-08-11"), endDate: new Date("2025-10-17"), isActive: false, gradesLocked: false, status: "planificacion" },
    { name: "Bimestre IV", number: 4, startDate: new Date("2025-10-20"), endDate: new Date("2025-12-19"), isActive: false, gradesLocked: false, status: "planificacion" }
  ],
  importantDates: [
    { name: "Inicio de clases", date: new Date("2025-03-03"), type: "academic" },
    { name: "Día del Maestro", date: new Date("2025-07-06"), type: "holiday" },
    { name: "Fiestas Patrias", date: new Date("2025-07-28"), type: "holiday" },
    { name: "Fin de año escolar", date: new Date("2025-12-19"), type: "academic" }
  ],
  isCurrent: true,
  status: "activo",
  isActive: true,
  stats: { totalStudents: 5, totalTeachers: 3, totalClassrooms: 3, totalCourses: 6 },
  createdAt: new Date(),
  updatedAt: new Date()
});
print("✓ Academic Year created");

// ===== 3. GRADE LEVELS =====
const gradeLevels = [];
const glData = [
  { name: "1° Primaria", shortName: "1°P", level: 1, type: "primaria", order: 1 },
  { name: "2° Primaria", shortName: "2°P", level: 2, type: "primaria", order: 2 },
  { name: "3° Primaria", shortName: "3°P", level: 3, type: "primaria", order: 3 },
  { name: "4° Primaria", shortName: "4°P", level: 4, type: "primaria", order: 4 },
  { name: "5° Primaria", shortName: "5°P", level: 5, type: "primaria", order: 5 },
  { name: "6° Primaria", shortName: "6°P", level: 6, type: "primaria", order: 6 },
  { name: "1° Secundaria", shortName: "1°S", level: 7, type: "secundaria", order: 7 },
  { name: "2° Secundaria", shortName: "2°S", level: 8, type: "secundaria", order: 8 },
  { name: "3° Secundaria", shortName: "3°S", level: 9, type: "secundaria", order: 9 },
  { name: "4° Secundaria", shortName: "4°S", level: 10, type: "secundaria", order: 10 },
  { name: "5° Secundaria", shortName: "5°S", level: 11, type: "secundaria", order: 11 },
];
glData.forEach(gl => {
  const id = ObjectId();
  gradeLevels.push(id);
  db.gradelevels.insertOne({
    _id: id, institution: instId.toString(), ...gl, description: "", isActive: true, createdAt: new Date(), updatedAt: new Date()
  });
});
print("✓ " + gradeLevels.length + " Grade Levels created");

// ===== 4. SUBJECTS =====
const subjectData = [
  { name: "Matemática", code: "MAT", area: "matematica", hoursPerWeek: 6, isRequired: true, color: "#4CAF50", icon: "calculate" },
  { name: "Comunicación", code: "COM", area: "comunicacion", hoursPerWeek: 6, isRequired: true, color: "#2196F3", icon: "menu_book" },
  { name: "Ciencia y Tecnología", code: "CYT", area: "ciencias", hoursPerWeek: 4, isRequired: true, color: "#FF9800", icon: "science" },
  { name: "Personal Social", code: "PS", area: "personal_social", hoursPerWeek: 4, isRequired: true, color: "#9C27B0", icon: "groups" },
  { name: "Educación Física", code: "EF", area: "educacion_fisica", hoursPerWeek: 3, isRequired: true, color: "#F44336", icon: "sports_soccer" },
  { name: "Arte y Cultura", code: "ART", area: "arte", hoursPerWeek: 2, isRequired: true, color: "#E91E63", icon: "palette" },
  { name: "Inglés", code: "ING", area: "comunicacion", hoursPerWeek: 3, isRequired: true, color: "#00BCD4", icon: "language" },
  { name: "Religión", code: "REL", area: "religion", hoursPerWeek: 2, isRequired: false, color: "#795548", icon: "church" },
];
const subjects = [];
subjectData.forEach(s => {
  const id = ObjectId();
  subjects.push({ id, ...s });
  db.subjects.insertOne({
    _id: id, institution: instId.toString(), ...s, description: s.name,
    gradeLevels: gradeLevels.map(g => g.toString()),
    applicableTo: "todos",
    defaultWeights: { examen: 40, tarea: 20, proyecto: 20, participacion: 10, practica: 10 },
    competencies: [], order: subjects.length, isActive: true,
    createdAt: new Date(), updatedAt: new Date()
  });
});
print("✓ " + subjects.length + " Subjects created");

// ===== 5. CLASSROOMS (3° Secundaria A, 4° Secundaria A, 5° Secundaria A) =====
const gl3s = gradeLevels[8]; // 3° Secundaria (index 8)
const gl4s = gradeLevels[9]; // 4° Secundaria (index 9)
const gl5s = gradeLevels[10]; // 5° Secundaria (index 10)

const classroom3A = ObjectId();
const classroom4A = ObjectId();
const classroom5A = ObjectId();

db.classrooms.insertMany([
  { _id: classroom3A, gradeLevel: gl3s.toString(), academicYear: ayId.toString(), section: "A", shift: "Mañana", tutor: docenteId.toString(), capacity: 35, location: { building: "Pabellón A", floor: "2", room: "201" }, stats: { enrolledStudents: 3, maleStudents: 2, femaleStudents: 1 }, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: classroom4A, gradeLevel: gl4s.toString(), academicYear: ayId.toString(), section: "A", shift: "Mañana", tutor: docente2Id.toString(), capacity: 35, location: { building: "Pabellón A", floor: "2", room: "202" }, stats: { enrolledStudents: 1, maleStudents: 0, femaleStudents: 1 }, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: classroom5A, gradeLevel: gl5s.toString(), academicYear: ayId.toString(), section: "A", shift: "Mañana", tutor: docente3Id.toString(), capacity: 35, location: { building: "Pabellón A", floor: "3", room: "301" }, stats: { enrolledStudents: 1, maleStudents: 1, femaleStudents: 0 }, isActive: true, createdAt: new Date(), updatedAt: new Date() },
]);
print("✓ 3 Classrooms created");

// ===== 6. STUDENTS =====
const student1 = ObjectId(); // Juan Perez (linked to alumnoId user)
const student2 = ObjectId(); // Sofia Ramirez
const student3 = ObjectId(); // Diego Torres
const student4 = ObjectId(); // Lucia Mendoza
const student5 = ObjectId(); // Mateo Herrera

db.students.insertMany([
  { _id: student1, firstName: "Juan", lastName: "Perez", dni: "55667788", email: "alumno@iepca.edu.pe", phone: "999555666", birthDate: new Date("2010-05-15"), gender: "M", photo: null, address: { street: "Jr. Los Olivos 123", district: "Continental Americano de Porres", city: "Lima", reference: "Cerca al parque" }, gradeLevel: "3° Secundaria", section: "A", studentCode: "EST-2025-0001", enrollmentNumber: "MAT-2025-001", guardians: [{ student: padreId.toString(), relationship: "padre", isPrimaryContact: true, canPickUp: true, isEmergencyContact: true }], medicalInfo: { bloodType: "O+", allergies: [], conditions: [], medications: [] }, status: "activo", isActive: true, userId: alumnoId.toString(), createdAt: new Date(), updatedAt: new Date() },
  { _id: student2, firstName: "Sofia", lastName: "Ramirez", dni: "66778899", email: "sofia.ramirez@iepca.edu.pe", phone: "998877663", birthDate: new Date("2010-08-22"), gender: "F", photo: null, address: { street: "Av. Peru 456", district: "Los Olivos", city: "Lima" }, gradeLevel: "3° Secundaria", section: "A", studentCode: "EST-2025-0002", enrollmentNumber: "MAT-2025-002", guardians: [{ student: padre2Id.toString(), relationship: "padre", isPrimaryContact: true, canPickUp: true, isEmergencyContact: true }], medicalInfo: { bloodType: "A+", allergies: [], conditions: [], medications: [] }, status: "activo", isActive: true, userId: alumno2Id.toString(), createdAt: new Date(), updatedAt: new Date() },
  { _id: student3, firstName: "Diego", lastName: "Torres", dni: "77889900", email: "diego.torres@iepca.edu.pe", phone: "998877664", birthDate: new Date("2010-03-10"), gender: "M", photo: null, address: { street: "Calle Las Flores 789", district: "Independencia", city: "Lima" }, gradeLevel: "3° Secundaria", section: "A", studentCode: "EST-2025-0003", enrollmentNumber: "MAT-2025-003", guardians: [], medicalInfo: { bloodType: "B+", allergies: ["Penicilina"], conditions: [], medications: [] }, status: "activo", isActive: true, userId: alumno3Id.toString(), createdAt: new Date(), updatedAt: new Date() },
  { _id: student4, firstName: "Lucia", lastName: "Mendoza", dni: "88990011", email: "lucia.mendoza@iepca.edu.pe", phone: "998877665", birthDate: new Date("2009-11-03"), gender: "F", photo: null, address: { street: "Jr. Union 321", district: "Continental Americano de Porres", city: "Lima" }, gradeLevel: "4° Secundaria", section: "A", studentCode: "EST-2025-0004", enrollmentNumber: "MAT-2025-004", guardians: [], medicalInfo: { bloodType: "AB+", allergies: [], conditions: [], medications: [] }, status: "activo", isActive: true, userId: alumno4Id.toString(), createdAt: new Date(), updatedAt: new Date() },
  { _id: student5, firstName: "Mateo", lastName: "Herrera", dni: "99001122", email: "mateo.herrera@iepca.edu.pe", phone: "998877666", birthDate: new Date("2008-07-19"), gender: "M", photo: null, address: { street: "Av. Tupac Amaru 567", district: "Comas", city: "Lima" }, gradeLevel: "5° Secundaria", section: "A", studentCode: "EST-2025-0005", enrollmentNumber: "MAT-2025-005", guardians: [], medicalInfo: { bloodType: "O-", allergies: [], conditions: [], medications: [] }, status: "activo", isActive: true, userId: alumno5Id.toString(), createdAt: new Date(), updatedAt: new Date() },
]);

// Link student profiles to user accounts
db.users.updateOne({ _id: alumnoId }, { $set: { studentProfile: student1.toString() } });
db.users.updateOne({ _id: alumno2Id }, { $set: { studentProfile: student2.toString() } });
db.users.updateOne({ _id: alumno3Id }, { $set: { studentProfile: student3.toString() } });
db.users.updateOne({ _id: alumno4Id }, { $set: { studentProfile: student4.toString() } });
db.users.updateOne({ _id: alumno5Id }, { $set: { studentProfile: student5.toString() } });
print("✓ 5 Students created");

// ===== 7. TEACHERS =====
const teacher1 = ObjectId(); // Carlos Rodriguez
const teacher2 = ObjectId(); // Ana Garcia
const teacher3 = ObjectId(); // Pedro Sanchez

db.teachers.insertMany([
  { _id: teacher1, firstName: "Carlos", lastName: "Rodriguez", dni: "87654321", email: "docente@iepca.edu.pe", phone: "999111222", birthDate: new Date("1985-06-15"), gender: "M", photo: null, address: { street: "Av. Universitaria 1234", district: "Continental Americano de Porres", city: "Lima" }, employeeCode: "DOC-2025-001", specialty: "Matemáticas", academicDegree: "Licenciado", professionalTitle: "Licenciado en Educación - Matemáticas", contractType: "nombrado", isActive: true, userId: docenteId.toString(), institution: instId.toString(), createdAt: new Date(), updatedAt: new Date() },
  { _id: teacher2, firstName: "Ana", lastName: "Garcia", dni: "22334455", email: "ana.garcia@iepca.edu.pe", phone: "998877661", birthDate: new Date("1990-02-28"), gender: "F", photo: null, address: { street: "Jr. Huascar 567", district: "Los Olivos", city: "Lima" }, employeeCode: "DOC-2025-002", specialty: "Comunicación", academicDegree: "Magister", professionalTitle: "Licenciada en Educación - Comunicación", contractType: "contratado", isActive: true, userId: docente2Id.toString(), institution: instId.toString(), createdAt: new Date(), updatedAt: new Date() },
  { _id: teacher3, firstName: "Pedro", lastName: "Sanchez", dni: "33445566", email: "pedro.sanchez@iepca.edu.pe", phone: "998877662", birthDate: new Date("1988-09-12"), gender: "M", photo: null, address: { street: "Calle Los Pinos 890", district: "Independencia", city: "Lima" }, employeeCode: "DOC-2025-003", specialty: "Ciencia y Tecnología", academicDegree: "Licenciado", professionalTitle: "Licenciado en Biología", contractType: "contratado", isActive: true, userId: docente3Id.toString(), institution: instId.toString(), createdAt: new Date(), updatedAt: new Date() },
]);
print("✓ 3 Teachers created");

// ===== 8. PARENTS =====
const parent1 = ObjectId(); // Maria Lopez
const parent2 = ObjectId(); // Roberto Ramirez

const defaultNotificationPrefs = {
  email: { grades: true, attendance: true, events: true, messages: false },
  push: { grades: true, attendance: true, events: true, messages: false },
  sms: { emergencies: true, attendance: false }
};

db.parents.insertMany([
  { _id: parent1, firstName: "Maria", lastName: "Lopez", dni: "11223344", email: "padre@iepca.edu.pe", phone: "999333444", birthDate: new Date("1980-04-20"), gender: "F", photo: null, address: { street: "Jr. Los Olivos 123", district: "Continental Americano de Porres", city: "Lima", reference: "Cerca al parque" }, occupation: "Contadora", workplace: "Empresa ABC SAC", children: [{ student: student1.toString(), relationship: "madre", isPrimaryContact: true, canPickUp: true, isEmergencyContact: true }], notifications: defaultNotificationPrefs, isActive: true, isVerified: true, userId: padreId.toString(), createdAt: new Date(), updatedAt: new Date() },
  { _id: parent2, firstName: "Roberto", lastName: "Ramirez", dni: "44556677", email: "roberto.ramirez@iepca.edu.pe", phone: "998877667", birthDate: new Date("1978-11-05"), gender: "M", photo: null, address: { street: "Av. Peru 456", district: "Los Olivos", city: "Lima" }, occupation: "Ingeniero", workplace: "Constructora XYZ", children: [{ student: student2.toString(), relationship: "padre", isPrimaryContact: true, canPickUp: true, isEmergencyContact: true }], notifications: defaultNotificationPrefs, isActive: true, isVerified: true, userId: padre2Id.toString(), createdAt: new Date(), updatedAt: new Date() },
]);

// Link children to parent users
db.users.updateOne({ _id: padreId }, { $set: { children: [{ student: student1.toString(), relationship: "madre", isPrimaryContact: true }] } });
db.users.updateOne({ _id: padre2Id }, { $set: { children: [{ student: student2.toString(), relationship: "padre", isPrimaryContact: true }] } });
print("✓ 2 Parents created");

// ===== 9. COURSES (6 courses for 3° Secundaria A) =====
const matSubj = subjects[0]; // Matemática
const comSubj = subjects[1]; // Comunicación
const cytSubj = subjects[2]; // CyT
const psSubj = subjects[3];  // Personal Social
const efSubj = subjects[4];  // Educación Física
const ingSubj = subjects[6]; // Inglés

const students3A = [student1.toString(), student2.toString(), student3.toString()];

const course1 = ObjectId();
const course2 = ObjectId();
const course3 = ObjectId();
const course4 = ObjectId();
const course5 = ObjectId();
const course6 = ObjectId();

db.courses.insertMany([
  { _id: course1, name: "Matemática - 3°A", code: "MAT-3A-2025", description: "Matemática para 3° Secundaria A", gradeLevel: "3° Secundaria", section: "A", teacher: docenteId.toString(), students: students3A, schedule: [{ day: "Lunes", startTime: "08:00", endTime: "09:30", classroom: "201" }, { day: "Miércoles", startTime: "08:00", endTime: "09:30", classroom: "201" }, { day: "Viernes", startTime: "08:00", endTime: "09:30", classroom: "201" }], evaluationWeights: { examen: 40, tarea: 20, proyecto: 20, participacion: 10, practica: 10 }, academicYear: 2025, period: "Anual", isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: course2, name: "Comunicación - 3°A", code: "COM-3A-2025", description: "Comunicación para 3° Secundaria A", gradeLevel: "3° Secundaria", section: "A", teacher: docente2Id.toString(), students: students3A, schedule: [{ day: "Lunes", startTime: "09:45", endTime: "11:15", classroom: "201" }, { day: "Jueves", startTime: "08:00", endTime: "09:30", classroom: "201" }], evaluationWeights: { examen: 40, tarea: 20, proyecto: 20, participacion: 10, practica: 10 }, academicYear: 2025, period: "Anual", isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: course3, name: "Ciencia y Tecnología - 3°A", code: "CYT-3A-2025", description: "CyT para 3° Secundaria A", gradeLevel: "3° Secundaria", section: "A", teacher: docente3Id.toString(), students: students3A, schedule: [{ day: "Martes", startTime: "08:00", endTime: "09:30", classroom: "Lab-1" }, { day: "Jueves", startTime: "09:45", endTime: "11:15", classroom: "Lab-1" }], evaluationWeights: { examen: 40, tarea: 20, proyecto: 20, participacion: 10, practica: 10 }, academicYear: 2025, period: "Anual", isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: course4, name: "Personal Social - 3°A", code: "PS-3A-2025", description: "Personal Social para 3° Secundaria A", gradeLevel: "3° Secundaria", section: "A", teacher: docenteId.toString(), students: students3A, schedule: [{ day: "Martes", startTime: "09:45", endTime: "11:15", classroom: "201" }, { day: "Viernes", startTime: "09:45", endTime: "11:15", classroom: "201" }], evaluationWeights: { examen: 40, tarea: 20, proyecto: 20, participacion: 10, practica: 10 }, academicYear: 2025, period: "Anual", isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: course5, name: "Educación Física - 3°A", code: "EF-3A-2025", description: "Educación Física para 3° Secundaria A", gradeLevel: "3° Secundaria", section: "A", teacher: docente3Id.toString(), students: students3A, schedule: [{ day: "Miércoles", startTime: "09:45", endTime: "11:15", classroom: "Cancha" }], evaluationWeights: { examen: 20, tarea: 10, proyecto: 20, participacion: 30, practica: 20 }, academicYear: 2025, period: "Anual", isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { _id: course6, name: "Inglés - 3°A", code: "ING-3A-2025", description: "Inglés para 3° Secundaria A", gradeLevel: "3° Secundaria", section: "A", teacher: docente2Id.toString(), students: students3A, schedule: [{ day: "Miércoles", startTime: "11:30", endTime: "13:00", classroom: "201" }, { day: "Viernes", startTime: "11:30", endTime: "13:00", classroom: "201" }], evaluationWeights: { examen: 40, tarea: 20, proyecto: 20, participacion: 10, practica: 10 }, academicYear: 2025, period: "Anual", isActive: true, createdAt: new Date(), updatedAt: new Date() },
]);
print("✓ 6 Courses created");

// ===== 10. ENROLLMENTS =====
db.enrollments.insertMany([
  { student: student1.toString(), classroom: classroom3A.toString(), academicYear: ayId.toString(), enrollmentDate: new Date("2025-02-15"), enrollmentNumber: "MAT-2025-001", status: "matriculado", enrollmentType: "regular", isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { student: student2.toString(), classroom: classroom3A.toString(), academicYear: ayId.toString(), enrollmentDate: new Date("2025-02-15"), enrollmentNumber: "MAT-2025-002", status: "matriculado", enrollmentType: "regular", isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { student: student3.toString(), classroom: classroom3A.toString(), academicYear: ayId.toString(), enrollmentDate: new Date("2025-02-16"), enrollmentNumber: "MAT-2025-003", status: "matriculado", enrollmentType: "regular", isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { student: student4.toString(), classroom: classroom4A.toString(), academicYear: ayId.toString(), enrollmentDate: new Date("2025-02-16"), enrollmentNumber: "MAT-2025-004", status: "matriculado", enrollmentType: "regular", isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { student: student5.toString(), classroom: classroom5A.toString(), academicYear: ayId.toString(), enrollmentDate: new Date("2025-02-17"), enrollmentNumber: "MAT-2025-005", status: "matriculado", enrollmentType: "regular", isActive: true, createdAt: new Date(), updatedAt: new Date() },
]);
print("✓ 5 Enrollments created");

// ===== 11. EVALUATIONS (Bimestre 1 & 2 for Matemática) =====
const eval1 = ObjectId();
const eval2 = ObjectId();
const eval3 = ObjectId();
const eval4 = ObjectId();
const eval5 = ObjectId();
const eval6 = ObjectId();

db.evaluations.insertMany([
  { _id: eval1, course: course1.toString(), teacher: docenteId.toString(), name: "Examen Parcial B1", type: "examen", bimester: 1, maxGrade: 20, weight: 2.0, date: new Date("2025-04-01"), description: "Ecuaciones lineales", academicYear: 2025, isActive: true, order: 1, createdAt: new Date(), updatedAt: new Date() },
  { _id: eval2, course: course1.toString(), teacher: docenteId.toString(), name: "Tarea 1 - B1", type: "tarea", bimester: 1, maxGrade: 20, weight: 1.0, date: new Date("2025-03-15"), description: "Ejercicios cap 1-3", academicYear: 2025, isActive: true, order: 2, createdAt: new Date(), updatedAt: new Date() },
  { _id: eval3, course: course1.toString(), teacher: docenteId.toString(), name: "Proyecto B1", type: "proyecto", bimester: 1, maxGrade: 20, weight: 1.5, date: new Date("2025-04-20"), description: "Proyecto de aplicación", academicYear: 2025, isActive: true, order: 3, createdAt: new Date(), updatedAt: new Date() },
  { _id: eval4, course: course1.toString(), teacher: docenteId.toString(), name: "Examen Parcial B2", type: "examen", bimester: 2, maxGrade: 20, weight: 2.0, date: new Date("2025-06-10"), description: "Funciones y gráficas", academicYear: 2025, isActive: true, order: 1, createdAt: new Date(), updatedAt: new Date() },
  { _id: eval5, course: course1.toString(), teacher: docenteId.toString(), name: "Tarea 1 - B2", type: "tarea", bimester: 2, maxGrade: 20, weight: 1.0, date: new Date("2025-05-20"), description: "Ejercicios funciones", academicYear: 2025, isActive: true, order: 2, createdAt: new Date(), updatedAt: new Date() },
  { _id: eval6, course: course1.toString(), teacher: docenteId.toString(), name: "Práctica B2", type: "practica", bimester: 2, maxGrade: 20, weight: 1.0, date: new Date("2025-06-25"), description: "Práctica calificada", academicYear: 2025, isActive: true, order: 3, createdAt: new Date(), updatedAt: new Date() },
]);
print("✓ 6 Evaluations created");

// ===== 12. GRADES (Bimestre 1 completed, Bimestre 2 in progress) =====
db.grades.insertMany([
  // Bimestre 1 - Juan Perez
  { student: student1.toString(), course: course1.toString(), bimester: 1, academicYear: 2025, scores: [{ evaluationId: eval1.toString(), score: 16, weight: 2.0 }, { evaluationId: eval2.toString(), score: 18, weight: 1.0 }, { evaluationId: eval3.toString(), score: 15, weight: 1.5 }], average: 16.1, status: "cerrado", teacher: docenteId.toString(), closedAt: new Date("2025-05-09"), createdAt: new Date(), updatedAt: new Date() },
  // Bimestre 1 - Sofia Ramirez
  { student: student2.toString(), course: course1.toString(), bimester: 1, academicYear: 2025, scores: [{ evaluationId: eval1.toString(), score: 14, weight: 2.0 }, { evaluationId: eval2.toString(), score: 16, weight: 1.0 }, { evaluationId: eval3.toString(), score: 17, weight: 1.5 }], average: 15.4, status: "cerrado", teacher: docenteId.toString(), closedAt: new Date("2025-05-09"), createdAt: new Date(), updatedAt: new Date() },
  // Bimestre 1 - Diego Torres
  { student: student3.toString(), course: course1.toString(), bimester: 1, academicYear: 2025, scores: [{ evaluationId: eval1.toString(), score: 12, weight: 2.0 }, { evaluationId: eval2.toString(), score: 10, weight: 1.0 }, { evaluationId: eval3.toString(), score: 13, weight: 1.5 }], average: 11.9, status: "cerrado", teacher: docenteId.toString(), closedAt: new Date("2025-05-09"), createdAt: new Date(), updatedAt: new Date() },
  // Bimestre 2 - Juan Perez (in progress)
  { student: student1.toString(), course: course1.toString(), bimester: 2, academicYear: 2025, scores: [{ evaluationId: eval4.toString(), score: 17, weight: 2.0 }, { evaluationId: eval5.toString(), score: 19, weight: 1.0 }], average: 17.7, status: "abierto", teacher: docenteId.toString(), createdAt: new Date(), updatedAt: new Date() },
  // Bimestre 2 - Sofia Ramirez (in progress)
  { student: student2.toString(), course: course1.toString(), bimester: 2, academicYear: 2025, scores: [{ evaluationId: eval4.toString(), score: 15, weight: 2.0 }, { evaluationId: eval5.toString(), score: 17, weight: 1.0 }], average: 15.7, status: "abierto", teacher: docenteId.toString(), createdAt: new Date(), updatedAt: new Date() },
]);
print("✓ 5 Grades created");

// ===== 13. ATTENDANCE (last 5 school days for Matemática) =====
const today = new Date();
const attendanceDates = [
  new Date(today.getFullYear(), today.getMonth(), today.getDate()),
  new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
  new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2),
  new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3),
  new Date(today.getFullYear(), today.getMonth(), today.getDate() - 4)
];
const attendanceRecords = [];
attendanceDates.forEach(d => {
  students3A.forEach((sid, idx) => {
    let status = "present";
    let arrivalTime = "07:55";
    if (d === "2025-06-04" && idx === 2) { status = "absent"; arrivalTime = null; }
    if (d === "2025-06-09" && idx === 1) { status = "late"; arrivalTime = "08:12"; }
    attendanceRecords.push({
      student: sid, course: course1.toString(), teacher: docenteId.toString(), date: d,
      status, arrivalTime, observations: status === "absent" ? "Sin justificación" : "",
      createdAt: new Date(), updatedAt: new Date()
    });
  });
});
db.attendances.insertMany(attendanceRecords);
print("✓ " + attendanceRecords.length + " Attendance records created");

// ===== 14. EVENTS =====
db.events.insertMany([
  { title: "Examen Parcial - Matemática 3°A", date: "2025-06-20", time: "08:00", type: "exam", description: "Examen del segundo bimestre de Matemática", location: "Aula 201", participants: students3A, notifyStudents: true, notifyParents: true, notifyTeachers: false, createdBy: docenteId.toString(), isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { title: "Reunión de Padres de Familia", date: "2025-06-25", time: "18:00", type: "meeting", description: "Reunión informativa del segundo bimestre", location: "Auditorio", participants: [], notifyStudents: false, notifyParents: true, notifyTeachers: true, createdBy: adminId.toString(), isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { title: "Día de la Bandera", date: "2025-06-07", time: "09:00", type: "activity", description: "Ceremonia por el Día de la Bandera", location: "Patio central", participants: [], notifyStudents: true, notifyParents: true, notifyTeachers: true, createdBy: adminId.toString(), isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { title: "Feriado - Día del Maestro", date: "2025-07-06", time: "", type: "holiday", description: "No hay clases", location: "", participants: [], notifyStudents: true, notifyParents: true, notifyTeachers: true, createdBy: adminId.toString(), isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { title: "Entrega de Proyecto - CyT", date: "2025-06-30", time: "11:00", type: "deadline", description: "Fecha límite para entregar el proyecto de ciencias", location: "Laboratorio 1", participants: students3A, notifyStudents: true, notifyParents: false, notifyTeachers: false, createdBy: docente3Id.toString(), isActive: true, createdAt: new Date(), updatedAt: new Date() },
]);
print("✓ 5 Events created");

// ===== 15. NOTIFICATIONS =====
db.notifications.insertMany([
  { recipient: alumnoId.toString(), title: "Nota publicada", message: "Se ha publicado tu nota del Examen Parcial B1 de Matemática: 16", type: "grade", data: { courseId: course1.toString(), bimester: 1 }, isRead: true, readAt: new Date("2025-05-10"), createdAt: new Date("2025-05-09"), updatedAt: new Date() },
  { recipient: alumnoId.toString(), title: "Próximo examen", message: "Tienes un examen de Matemática el 20 de junio a las 08:00", type: "event", data: {}, isRead: false, createdAt: new Date(), updatedAt: new Date() },
  { recipient: padreId.toString(), title: "Notas del Bimestre I", message: "Las notas del primer bimestre de Juan Perez ya están disponibles", type: "grade", data: { studentId: student1.toString() }, isRead: true, readAt: new Date("2025-05-10"), createdAt: new Date("2025-05-09"), updatedAt: new Date() },
  { recipient: padreId.toString(), title: "Reunión de padres", message: "Se ha programado una reunión de padres para el 25 de junio a las 18:00", type: "event", data: {}, isRead: false, createdAt: new Date(), updatedAt: new Date() },
  { recipient: docenteId.toString(), title: "Cierre de notas", message: "Recuerde cerrar las notas del Bimestre II antes del 18 de julio", type: "info", data: {}, isRead: false, createdAt: new Date(), updatedAt: new Date() },
  { recipient: adminId.toString(), title: "Resumen semanal", message: "95% de asistencia esta semana. 3 justificaciones pendientes.", type: "info", data: {}, isRead: false, createdAt: new Date(), updatedAt: new Date() },
]);
print("✓ 6 Notifications created");

// ===== 16. JUSTIFICATION =====
db.justifications.insertOne({
  student: student3.toString(), parent: null, dates: [new Date("2025-06-04")],
  reason: "Enfermedad", observations: "El alumno presentó malestar estomacal",
  documents: [], coursesAffected: [course1.toString()],
  status: "pending", createdAt: new Date(), updatedAt: new Date()
});
print("✓ 1 Justification created");

// ===== SUMMARY =====
print("\n========================================");
print("  SEED DATA COMPLETE");
print("========================================");
print("Institution: IEP Continental Americano");
print("Academic Year: 2025 (Bimestre II activo)");
print("Grade Levels: 11 (6 primaria + 5 secundaria)");
print("Subjects: 8");
print("Classrooms: 3 (3°A, 4°A, 5°A Secundaria)");
print("Users: 11 total");
print("Students: 5 | Teachers: 3 | Parents: 2");
print("Courses: 6 (3° Secundaria A)");
print("Enrollments: 5");
print("Evaluations: 6 | Grades: 5");
print("Attendance: 15 records");
print("Events: 5 | Notifications: 6");
print("Justifications: 1");
print("========================================");
print("\nTest Accounts:");
print("  admin@iepca.edu.pe / Admin123! (administrativo)");
print("  docente@iepca.edu.pe / Docente123! (docente)");
print("  padre@iepca.edu.pe / Padre123! (padre)");
print("  alumno@iepca.edu.pe / Alumno123! (estudiante)");
print("========================================");
